---

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :none
  :use_auxiliary_dependencies: TRUE
  :build_root: build/ceedling
  :release_build: FALSE
  :test_file_prefix: test_

:extension:
  :executable: .out

:paths:
  :test:
    - test/**
  :source:
    - test/support/**
    - src/hal/subtitle_bram/**
    - src/hal/subtitle_overlay/**
    - src/hal/usb_audio/**
    - src/qpc/ports/posix-qv/**
    - src/qpc/src/qf/**
    - src/svc/system/**
    - src/svc/stt/**
    - src/svc/subtitle_pipeline/**
    - src/svc/usb_audio/**
    - src/svc/video_pipeline/**
    - src/utils/log/**
    - src/utils/number_parse/**
  :include:
    - linux/include/uapi
    - src/bsp/bsp_compat
    - src/bsp/platform
    - src/bsp/platform/linux
    - src/bsp/vtc_v7_2/src
    - src/qpc/include
    - src/qpc/ports/posix-qv
    - src/qpc/ports/config
    - src/app
    - src/hal/subtitle_bram
    - src/hal/subtitle_overlay
    - src/hal/video_dma
    - src/hal/video_dynclk
    - src/hal/video_gpio
    - src/hal/video_vtc
    - src/hal/usb_audio
    - src/svc/stt
    - src/svc/system
    - src/svc/subtitle_pipeline
    - src/svc/usb_audio
    - src/svc/video_pipeline
    - test/support
    - src/utils/log
    - src/utils/number_parse

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :expect_any_args
    - :return_thru_ptr

:flags:
  :test:
    :compile:
      :*:
        - -std=gnu99
        - -Wall
        - -Wextra
        - -fprofile-arcs
        - -ftest-coverage
    :link:
      :*:
        - -fprofile-arcs
        - -ftest-coverage
        - -lgcov
        - -pthread

:plugins:
  :enabled:
    - gcov

:gcov:
  :reports:
    - HtmlDetailed
    - Text
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90
